# Generated by Django 3.1.6 on 2021-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=7)),
                ('year', models.CharField(default='2021', max_length=4)),
                ('month', models.CharField(default='January', max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=30)),
                ('betting', models.CharField(default='Las Vegas/Online', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('year', 'season', 'month', 'name', 'location', 'betting', 'created_at', 'updated_at'),
            },
        ),
    ]
