# Generated by Django 3.1.6 on 2021-08-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210813_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('season', 'month', 'name', 'betting', 'created_at', 'updated_at')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
