# Generated by Django 3.1.6 on 2021-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210813_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('season', 'month', 'name', 'details', 'betting', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
