# Generated by Django 3.1.6 on 2021-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'name', 'description', 'price', 'image', 'colors', 'types', 'sex', 'sizes', 'quantity', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Red', 'Red'), ('Blue', 'Blue')], default='White', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('XS', 'SX'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Long-Sleeve Shirt', 'Long-Sleeve Shirt'), ('Sweatshirt', 'Sweatshirt'), ('Jacket', 'Jacket'), ('Hat', 'Hat')], default='T-Shirt', max_length=255),
        ),
    ]
